#Make sure you create directory and do: git init, git add . git commit -m "adding config"
#spring.cloud.config.server.git.uri: "C://Softwares//cloudconfig"
spring.cloud.config.server.git.uri: "https://github.com/chauhan1212/cloud-config"
# you must have to define master branch in github to get it work.
server.port: 8888